### ISSUE TITLE
"View Steam Profile" 64bit steam id is wrong.

### ISSUE THREAD

**Issue by Bubka3** [ppalex7/SourceComms#61]
https://www.aocgamers.com/sourcebans/comms#15

Something is wrong with all of the View Profile links.
http://steamcommunity.com/profiles/7.6561197984774E+16

**Comment by ppalex7** [comment]
damn php on 32bit systems (

**Comment by ppalex7** [comment]
Fixed. Please check.

**Comment by Bubka3** [comment]
The regular sourcebans, the 64bit steam id profile link works fine. You should see how its done there and do same for consistency.

**Comment by ppalex7** [comment]
In Sourcebans getting 64bit community id was implemented as SQL-query (!) to database. I think that this is not good practice.

**Comment by Bubka3** [comment]
You already made a SQL query to load length and reason. I doubt adding the steam ID in the select statement would be "bad practice".

**Comment by ppalex7** [comment]
The problem is not in additional field to select, but it is in the way of getting id in query - string and math operations, that looks terrible for me.

What's wrong with 32bit community id link? It is also native to the data, that sourcecomms stores in db (it saves 32bit steam account id, not steamid)
